package AProgramsPorblems;

import java.util.ArrayList;
import java.util.List;

public class DuplicateNumberCount1 {

	public static void main(String arg[]) {
		long stTIme = System.currentTimeMillis();

		String test = "AAabcder";
		/*
		 * String test =
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbd"
		 * +
		 * "ddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabb"
		 * +
		 * "dddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaa"
		 * +
		 * "eaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbddd"
		 * +
		 * "aaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * +
		 * "aabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaaeaabbdddaae"
		 * ;
		 */
		if (null != test && test != "") {
			getStringCount(test);
		} else {
			System.out.println("NOT A VALID STRING");
		}

		long EndTIme = System.currentTimeMillis();
		System.out.println(EndTIme - stTIme);
		System.out.println(test.length());

	}

	private static void getStringCount(String test) {
		List<Integer> list = new ArrayList<Integer>();
		List<Character> listString = new ArrayList<Character>();
		char previousChar = test.charAt(0);

		int sum = 0;
		for (int i = 0; i < test.length(); i++) {
			if (i == 0) {
				listString.add(test.charAt(0));
				list.add(1);
			} else {
				if (previousChar == test.charAt(i)) {
					list.set((list.size() - 1), list.get(list.size() - 1) + 1);
				} else {
					listString.add(test.charAt(i));
					list.add(1);
				}
			}
			previousChar = test.charAt(i);
		}
		printString(listString, list);
	}

	private static void printString(List<Character> listString,
			List<Integer> list) {
		StringBuffer sb = new StringBuffer();
		for (int i = 0; i < listString.size(); i++) {
			sb.append(listString.get(i));
			sb.append(list.get(i));
		}
		System.out.println(sb.toString());
	}

}
